/**
 * Generate interop fixtures for the Python reconciler's crypto tests.
 *
 * The Python side must open boxes sealed by THIS implementation. Hand-written
 * fixtures would only prove Python agrees with itself, so these are produced by
 * the real Node code and committed. Regenerate with `pnpm gen:crypto-fixtures`
 * only when the wire format deliberately changes — a diff here means every
 * stored token becomes unreadable.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { aad, EnvKeyring, generateDek, seal } from '@onelineflow/crypto';

const ROOT_KEY_B64 = Buffer.alloc(32, 7).toString('base64');
const TENANT_A = '11111111-1111-4111-8111-111111111111';
const TENANT_B = '22222222-2222-4222-8222-222222222222';

async function main(): Promise<void> {
  const keyring = new EnvKeyring(ROOT_KEY_B64, 1);
  const dek = generateDek();
  const { wrapped, keyVersion } = await keyring.wrapDek(dek);

  const accessToken = 'ya29.fake-access-token-for-interop-testing';
  const refreshToken = 'AB11fake-refresh-token-for-interop-testing';

  const fixtures = {
    note: 'Generated by scripts/gen-crypto-fixtures.ts. Do not hand-edit.',
    rootKeyB64: ROOT_KEY_B64,
    keyVersion,
    wrappedDekB64: wrapped.toString('base64'),
    tenantA: TENANT_A,
    tenantB: TENANT_B,
    accessTokenPlain: accessToken,
    accessTokenSealedB64: seal(accessToken, dek, aad(TENANT_A, 'qbo-token')).toString('base64'),
    refreshTokenPlain: refreshToken,
    refreshTokenSealedB64: seal(refreshToken, dek, aad(TENANT_A, 'qbo-token')).toString('base64'),
    // Sealed for tenant B: Python must FAIL to open this with tenant A's AAD.
    wrongTenantSealedB64: seal(accessToken, dek, aad(TENANT_B, 'qbo-token')).toString('base64'),
    // Sealed with a different purpose: must also fail.
    wrongPurposeSealedB64: seal(accessToken, dek, aad(TENANT_A, 'other')).toString('base64'),
    unicodePlain: 'Café Übergrößen 日本語 — token',
    unicodeSealedB64: seal(
      'Café Übergrößen 日本語 — token',
      dek,
      aad(TENANT_A, 'qbo-token'),
    ).toString('base64'),
  };

  const target = fileURLToPath(
    new URL('../python/reconciler/tests/fixtures/crypto_interop.json', import.meta.url),
  );
  writeFileSync(target, `${JSON.stringify(fixtures, null, 2)}\n`);
  process.stdout.write(`wrote ${target}\n`);
}

void main();
